# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ax-darwin-arm64 = {
    pname = "ax-darwin-arm64";
    version = "v0.1.21";
    src = fetchurl {
      url = "https://github.com/yusukebe/ax/releases/download/v0.1.21/ax-darwin-arm64";
      sha256 = "sha256-cjLX9MG8lri8nCFp7oL2JpUxxMbJQeNRIXeZoDThj6c=";
    };
  };
}
