# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ax-darwin-arm64 = {
    pname = "ax-darwin-arm64";
    version = "v0.1.25";
    src = fetchurl {
      url = "https://github.com/yusukebe/ax/releases/download/v0.1.25/ax-darwin-arm64";
      sha256 = "sha256-lGM/nWHHQ8/89R5TOCidl0whQo77cL0plebG7BPgYsE=";
    };
  };
  chrome-devtools-mcp = {
    pname = "chrome-devtools-mcp";
    version = "1.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/chrome-devtools-mcp/-/chrome-devtools-mcp-1.6.0.tgz";
      sha256 = "sha256-HmMsLZcUtPgrTPq077nOV1CFx1/+XpdyODEprwEsnIQ=";
    };
  };
  gh-sub-issue-darwin-arm64 = {
    pname = "gh-sub-issue-darwin-arm64";
    version = "0.5.1";
    src = fetchurl {
      url = "https://github.com/yahsan2/gh-sub-issue/releases/download/v0.5.1/gh-sub-issue_0.5.1_darwin-arm64";
      sha256 = "sha256-UmVEz2zi7kZF0horOEfP4bZUhA/hwAuE5xrKgZHVSAc=";
    };
  };
  gwq-darwin-arm64 = {
    pname = "gwq-darwin-arm64";
    version = "v0.1.1";
    src = fetchurl {
      url = "https://github.com/d-kuro/gwq/releases/download/v0.1.1/gwq_Darwin_arm64.tar.gz";
      sha256 = "sha256-G4tYAEvOL/G4WxJG5rOxTsqJoKlYeWlu5sdc9I571/s=";
    };
  };
  octorus-darwin-arm64 = {
    pname = "octorus-darwin-arm64";
    version = "0.7.2";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.7.2/octorus-0.7.2-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-Uv5MKlwgZqG1XaS75yZ5QkVJ8nqlwjWndN9LAv5ZIAI=";
    };
  };
  playwright-cli = {
    pname = "playwright-cli";
    version = "v0.1.18";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "playwright-cli";
      rev = "v0.1.18";
      fetchSubmodules = false;
      sha256 = "sha256-E/AzDJhD12PWSaA3iRY+hloPsSWnAw18gTa/ItVhr3E=";
    };
  };
  vite-plus-darwin-arm64 = {
    pname = "vite-plus-darwin-arm64";
    version = "v0.2.8";
    src = fetchurl {
      url = "https://github.com/voidzero-dev/vite-plus/releases/download/v0.2.8/vp-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-GjQ2NIq1gnFnMtKT1RGrm3D1xzBpUf5PpvbIrHThHmI=";
    };
  };
  vize-darwin-arm64 = {
    pname = "vize-darwin-arm64";
    version = "v0.345.0";
    src = fetchurl {
      url = "https://github.com/ubugeeei-prod/vize/releases/download/v0.345.0/vize-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-lbSslNFH4dCS0WgMlYgNjaF1oEMrvOkygyIgb9t3NPk=";
    };
  };
}
