# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ax-darwin-arm64 = {
    pname = "ax-darwin-arm64";
    version = "v0.1.21";
    src = fetchurl {
      url = "https://github.com/yusukebe/ax/releases/download/v0.1.21/ax-darwin-arm64";
      sha256 = "sha256-cjLX9MG8lri8nCFp7oL2JpUxxMbJQeNRIXeZoDThj6c=";
    };
  };
  octorus-darwin-arm64 = {
    pname = "octorus-darwin-arm64";
    version = "0.6.7";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.6.7/octorus-0.6.7-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-fsqnB49TnsPG9waafix0ILJHjslGJEmAPc2EiJS0g+Y=";
    };
  };
  vite-plus-darwin-arm64 = {
    pname = "vite-plus-darwin-arm64";
    version = "v0.2.6";
    src = fetchurl {
      url = "https://github.com/voidzero-dev/vite-plus/releases/download/v0.2.6/vp-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-2m07OPIdNyIhrg/jsI4dTRePIkPHlHmim+FzLXZm0eo=";
    };
  };
  vize-darwin-arm64 = {
    pname = "vize-darwin-arm64";
    version = "v0.291.0";
    src = fetchurl {
      url = "https://github.com/ubugeeei-prod/vize/releases/download/v0.291.0/vize-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-UnEUAxlmJVUdqwDs6iASlOfC5WAQdH55QCYx9+i/SVQ=";
    };
  };
}
