# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ax-darwin-arm64 = {
    pname = "ax-darwin-arm64";
    version = "v0.1.25";
    src = fetchurl {
      url = "https://github.com/yusukebe/ax/releases/download/v0.1.25/ax-darwin-arm64";
      sha256 = "sha256-lGM/nWHHQ8/89R5TOCidl0whQo77cL0plebG7BPgYsE=";
    };
  };
  chrome-devtools-mcp = {
    pname = "chrome-devtools-mcp";
    version = "1.8.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/chrome-devtools-mcp/-/chrome-devtools-mcp-1.8.0.tgz";
      sha256 = "sha256-rAM0QQzqddEaXrtVX7sBOaSjlN412YzCo7wKlZ8ATN0=";
    };
  };
  frog-darwin-arm64 = {
    pname = "frog-darwin-arm64";
    version = "1.1.0";
    src = fetchurl {
      url = "https://github.com/wevm/frog/releases/download/frog@1.1.0/frog-darwin-arm64.gz";
      sha256 = "sha256-9QbnCokyF7VHcRpyy/S9pnZ6FcI2YBzg1gAhlcI3+pM=";
    };
  };
  gh-sub-issue-darwin-arm64 = {
    pname = "gh-sub-issue-darwin-arm64";
    version = "0.5.1";
    src = fetchurl {
      url = "https://github.com/yahsan2/gh-sub-issue/releases/download/v0.5.1/gh-sub-issue_0.5.1_darwin-arm64";
      sha256 = "sha256-UmVEz2zi7kZF0horOEfP4bZUhA/hwAuE5xrKgZHVSAc=";
    };
  };
  gwq-darwin-arm64 = {
    pname = "gwq-darwin-arm64";
    version = "v0.1.1";
    src = fetchurl {
      url = "https://github.com/d-kuro/gwq/releases/download/v0.1.1/gwq_Darwin_arm64.tar.gz";
      sha256 = "sha256-G4tYAEvOL/G4WxJG5rOxTsqJoKlYeWlu5sdc9I571/s=";
    };
  };
  octorus-darwin-arm64 = {
    pname = "octorus-darwin-arm64";
    version = "0.7.2";
    src = fetchurl {
      url = "https://github.com/ushironoko/octorus/releases/download/v0.7.2/octorus-0.7.2-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-Uv5MKlwgZqG1XaS75yZ5QkVJ8nqlwjWndN9LAv5ZIAI=";
    };
  };
  playwright-cli = {
    pname = "playwright-cli";
    version = "v0.1.18";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "playwright-cli";
      rev = "v0.1.18";
      fetchSubmodules = false;
      sha256 = "sha256-E/AzDJhD12PWSaA3iRY+hloPsSWnAw18gTa/ItVhr3E=";
    };
  };
  vite-plus-darwin-arm64 = {
    pname = "vite-plus-darwin-arm64";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/voidzero-dev/vite-plus/releases/download/v0.3.0/vp-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-0+eh5oK2Qhbj2pOTcdclm4I47CHeQp0DmRwZg6gqlh4=";
    };
  };
  vize-darwin-arm64 = {
    pname = "vize-darwin-arm64";
    version = "v0.387.0";
    src = fetchurl {
      url = "https://github.com/ubugeeei-prod/vize/releases/download/v0.387.0/vize-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-kkftCZH4A8x/SmPwVOfHWJmkrob6u0pGL9VwSffD5yI=";
    };
  };
}
